### ISSUE TITLE
previewHtml is no longer available

### ISSUE THREAD

**Issue by supcik** [stef-levesque/vscode-3dviewer#9] opened 2019-04-19 09:04 UTC
Hello,

I just wanted to use your plugin on stl files, but when I "Open in Viewer", I get the following error (in the vscode developer tools):

```
ERR command 'vscode.previewHtml' not found: Error: command 'vscode.previewHtml' not found
```
I found that the `previewHtml` was [deprecated](https://github.com/Microsoft/vscode/issues/62630) and it seems that it is no longer available in the latest version of vscode.

Do you have a workaround or do you plan an updated version of your plugin ?

Thank you in advance for your reply.

**Comment by paulhayes** [comment] 2019-05-07 07:42
Yeah, would be great to see a fix for this. This was a useful extension.

**Comment by lwohlhart** [comment] 2019-05-20 09:31
yep really loved the extension we should definitely get it back on track

**Comment by stef-levesque** [comment] 2020-05-17 23:44
Hey, sorry for not maintaining the repo over the last few months.

I've stop trying to support webview, and now focus on using custom editor in the [custom-editorbranch](/stef-levesque/vscode-3dviewer/tree/feature/custom-editor)

I'll submit a fix for the extension when the proposed API is approved

Closing as a duplicate of #10

**Closed by stef-levesque** 2020-05-17 23:44 UTC
